// <auto-generated />
using System;
using CampusConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Migrations.Tables
{
    [DbContext(typeof(TablesDbContext))]
    partial class TablesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusConnect.Models.Attachments", b =>
                {
                    b.Property<int>("fileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fileID"));

                    b.Property<string>("contentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("creatorID")
                        .HasColumnType("int")
                        .HasColumnName("creatorID");

                    b.Property<string>("fileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("requestID")
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("fileID");

                    b.HasIndex("creatorID");

                    b.HasIndex("requestID");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("CampusConnect.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryID"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("categoryID");

                    b.ToTable("category");
                });

            modelBuilder.Entity("CampusConnect.Models.Request", b =>
                {
                    b.Property<int>("requestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestID"));

                    b.Property<int?>("assigned_to")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to");

                    b.Property<string>("buildingName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("categoryID")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<DateTime?>("closedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("roomNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("statusID")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("requestID");

                    b.HasIndex("assigned_to");

                    b.HasIndex("categoryID");

                    b.HasIndex("created_by");

                    b.HasIndex("statusID");

                    b.ToTable("request");
                });

            modelBuilder.Entity("CampusConnect.Models.RequestStatus", b =>
                {
                    b.Property<int>("statusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusID"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("statusID");

                    b.ToTable("requestStatus");
                });

            modelBuilder.Entity("CampusConnect.Models.Roles", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleID"));

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("roleID");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("CampusConnect.Models.Test_Brittany_BL", b =>
                {
                    b.Property<int>("testID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("testID");

                    b.ToTable("Test_Brittany_L");
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("department")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("userID");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("CampusConnect.Models.requestComments", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentID"));

                    b.Property<string>("commentText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("creatorID")
                        .HasColumnType("int")
                        .HasColumnName("creatorID");

                    b.Property<int>("requestID")
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    b.HasKey("commentID");

                    b.HasIndex("creatorID");

                    b.HasIndex("requestID");

                    b.ToTable("requestComments");
                });

            modelBuilder.Entity("CampusConnect.Models.userRoles", b =>
                {
                    b.Property<int>("roleID")
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    b.Property<int>("userID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("roleID", "userID");

                    b.HasIndex("userID");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("CampusConnect.Models.Attachments", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "creator")
                        .WithMany("attachments")
                        .HasForeignKey("creatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Request", "request")
                        .WithMany("attachments")
                        .HasForeignKey("requestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");

                    b.Navigation("request");
                });

            modelBuilder.Entity("CampusConnect.Models.Request", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "assignedTo")
                        .WithMany("requestsAssigned")
                        .HasForeignKey("assigned_to")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusConnect.Models.Category", "category")
                        .WithMany("requests")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "createdBy")
                        .WithMany("requestsCreated")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.RequestStatus", "status")
                        .WithMany("requests")
                        .HasForeignKey("statusID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("assignedTo");

                    b.Navigation("category");

                    b.Navigation("createdBy");

                    b.Navigation("status");
                });

            modelBuilder.Entity("CampusConnect.Models.requestComments", b =>
                {
                    b.HasOne("CampusConnect.Models.User", "creator")
                        .WithMany("comments")
                        .HasForeignKey("creatorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Request", "request")
                        .WithMany("comments")
                        .HasForeignKey("requestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");

                    b.Navigation("request");
                });

            modelBuilder.Entity("CampusConnect.Models.userRoles", b =>
                {
                    b.HasOne("CampusConnect.Models.Roles", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.User", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("CampusConnect.Models.Category", b =>
                {
                    b.Navigation("requests");
                });

            modelBuilder.Entity("CampusConnect.Models.Request", b =>
                {
                    b.Navigation("attachments");

                    b.Navigation("comments");
                });

            modelBuilder.Entity("CampusConnect.Models.RequestStatus", b =>
                {
                    b.Navigation("requests");
                });

            modelBuilder.Entity("CampusConnect.Models.Roles", b =>
                {
                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Navigation("attachments");

                    b.Navigation("comments");

                    b.Navigation("requestsAssigned");

                    b.Navigation("requestsCreated");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
